export default Strings = {
    HomeDemo: {
        Heading: "DemoOfRedux",
    },
    SideMenu: {
        Home: 'Home',
        Dashboard: 'Dashboard',
        Search: 'Search',
        Subscribe: 'Subscribe',
        Payment_History: 'Payment History',
        Discover: 'Discover',
        Notification: 'Notification',
        Friends: 'Friends',
        My_Match: 'My Match',
        Favourites: 'Favourites',
        Chat: 'Chat',
        My_Feed: 'My Feed',
        Block_List: 'Block List',
        Settings: 'Settings',
        Change_Password: 'Change Password',
        LogOut: 'LogOut',
    },
    Dashboard: {
        My_Photos: 'My Photos',
        Notification: 'Notification',
        Favourites: 'Favourites',
        My_Match: 'My Match',
        My_Friends: 'My Friends',
        Block_List: 'Block List',
        Chat: 'Chat',
        My_Feed: 'My Feed',
        Settings: 'Settings',
        UnlikeFeed: 'You have unliked feed successfully.',
        LikeFeed: 'You have liked feed successfully.',
        AlreadyReport: 'You have already Reported this Profile.',
        ApprovedReport: 'Your Report Approved.',
        AlertTitle: 'UGC Policy',
        Alertmessage: 'sdfmsknfkskfjnskfskjdbnfksdjfnksnfksdnfkjsnfkjsdn fksndfksdnfksfksdjfnsdkjnfdsnfkskjdfsdjfnsdkjnfskjdfksdfkjsdnfksdjfnksdnfkjdsnfkj'
    },
    MyPhotos: {
        PhotoNoteFound: 'No Photos Found.',
        MyPhoto: 'My Photos',
    },
    Login: {
        Dating: 'D a t i n g ',
        App: 'A p p',
        PhoneValidation: 'Phone or email is required.',
        PasswordValidation: 'Password is required.',
        ForgotValidation: 'Forgot Password?',
        Connect: 'OR CONNECT WITH',
        Facebook: 'FACEBOOK',
        Google: 'GOOGLE',
        Account: ` Don't have an account?`,
        Register: 'Register',
        ByClicking: 'By clicking "Login",you agree with our',
        Terms: 'terms',
        LearnHow: '.Learn how we process your data in our',
        Privacy_Policy: 'privacy policy',
        And: 'and',
        Cookie_Policy: 'cookies policy',
        Login: 'LOGIN',
        CredentialNotMatch: 'Credential does not match.',
        LoginSuccessfully: 'You are login successfully.',
        AccountDeactivate: 'Your account has been de-activated.',
        LoginFailed: 'Login failed with error: ',
        LoginCancelled: 'Login was cancelled',
        PlayService: 'PLAY SERVICES NOT AVAILABLE',
    },
    Register: {
        Register: 'R e g i s t e r',
        Account: 'A c c o u n t',
        FullNameValidation: 'Fullname is required.',
        EmailValidation: 'Email is required',
        PhoneValidation: 'Phone number is required',
        PassWordValidation: 'Password is required',
        ConfirmPassWordValidation: 'Confirm Password is required',
        AccountHave: ' Already have an account ?',
        Login: 'Login',
        RegisterButton: 'REGISTER',
        CountryRequired: 'Country is required.',
        RegisterSuccessfully: 'You are registered successfully.',
        CountrySelect: 'Please select country',
        SuccessfullySubscribed: 'Successfully subscribed to topic:',
        Unsuccessfully: 'unsuccessfully ',
    },
    RegisterStep1: {
        MyNick: 'My Nick',
        Name: 'Name is',
        NickRequired: 'Nickname is required.',
        ProfileName: 'This is the name shown on your profile.',
        Continue: 'CONTINUE',
    },
    RegisterStep2: {
        My: 'My',
        Birthday: 'Birthday is',
        AgePublic: 'Your age will be public.',
        Continue: 'CONTINUE',
        BirthDateRequired: 'Birth date is required.',
        BirthGreater: 'Birth date should be greater or equals to 18.',
    },
    RegisterStep3: {
        GenderRequired: 'Gender is required.',
        IAm: 'I am a',
        Man: 'MAN',
        Woman: 'WOMAN',
        GenderProfile: 'Your gender will be public on your profile',
        Continue: 'CONTINUE',
    },
    RegisterStep4: {
        ShowMe: 'Show me',
        Man: 'MAN',
        Woman: 'WOMAN',
        EveryOne: 'EVERYONE',
        Continue: 'CONTINUE',
        SelectOption: ' Please select a single option.',
    },
    RegisterStep5: {
        My: 'My',
        AddressIs: 'Address is',
        AddressShown: 'Your address will not be shown to other users.',

        Continue: 'CONTINUE',
    },
    RegisterStep6: {
        MyEducation: 'My education',
        QualificaationIs: 'qualification is',
        ShowProfile: 'This will show on your profile.',
        QualificaationRequired: 'Educational qualification is required.',
        YourQualificationRequired: 'Your qualification is required.',
        Continue: 'CONTINUE',
    },
    RegisterStep7: {
        My: 'My',
        HobbiesAre: 'hobbies are ',
        SelectHobby: 'Select Hobby',
        HobbyRequired: 'Hobby is required.',
        AddHobbies: 'Add hobbies',
        Next: 'Next',
    },
    RegisterStep8: {
        AddPhotos: 'Add photos',
        HoldReorder: 'Hold, drag and drop to reorder',
        Continue: 'CONTINUE',
    },
    SocialHabitsScreen: {
        Social: 'Social',
        Habits: 'Habits',
        Smoking: 'Smoking',
        Drinking: 'Drinking',
        Continue: 'CONTINUE',
        SocialHabits: 'Social habits are required.',
    },
    SelectHobbiesSignUp: {
        SelectHobby: 'Select Hobby',
        Continue: 'CONTINUE',
        SelectOne: 'Please Select Atleast One Hobby.',
    },
    MyInterest: {
        My: 'My',
        Intrest: 'Intrest',
        Relationship: 'Relationship',
        JustFriend: 'Just Friend',
        WillSee: 'Will See',
        Continue: 'CONTINUE',
        IntrestRequired: 'Interest is required.',
    },
    RegistrationFinalStep: {
        Welcome: 'Welcome to Afronection',
        FollowRules: 'Please follow the house rules.',
        Yourself: 'Be yourself.',
        TrueInformation: 'Make sure your photos,age and bio are true to who you are.',
        StaySafe: 'Stay safe.',
        DateSafely: 'Dont be too quick to give out personal information. Date safely',
        PlayCool: 'Play it cool.',
        RespectAndTreat: 'Respect others and treat them as you would like to be treated.',
        Proactive: 'Be proactive.',
        BadBehaviour: 'Always report bad behaviour.',
        I: 'I',
        Agree: 'AGREE',
        UpdatedSuccessfully: 'Your profile is updated successfully.',
    },
    EditHobby: {
        Add: 'Add',
    },
    RegistrationEmail: {
        MyEmail: 'My Email',
        IdIs: 'Id is',
        ItAppear: 'This is show. It will appear in the app.',
        Continue: 'CONTINUE',
    },
    RegistrationMobile: {
        MyMobile: 'My Mobile',
        NumberIs: 'Number is',
        ItAppear: 'This is show. It will appear in the app.',
        Continue: 'CONTINUE',
    },
    AcceptFriendRequest: {
        Title: 'Successfully added',
        SubTitle: 'on your friends list.',
    },
    AddedToFavourite: {
        Title: 'Has Added',
        SubTitle: 'to Your Favorite',
        Favourite: 'MY FAVORITES',
    },
    AddedToSubscribe: {
        Title: 'Please subscribe',
        SubTitle: 'to access this content',
        Subscribe: 'SUBSCRIBE',
        NotNow: 'NOT NOW',
    },
    HobbyItem: {
        X: 'X'
    },
    AddHobby: {
        Add: 'Add',
    },
    AddHobbyEdit: {
        Add: 'Add',
    },
    BlockFriend: {
        BlockFriend: 'You have blocked friend successfully.',
        AreSure: 'Are you sure you',
        WantBlock: 'want to block',
        ThisFriend: 'this profile?',
        Confirm: 'CONFIRM',
    },
    ReportUser: {
        ReportUser: 'You have Report this user.',
        AreSure: 'Are you sure you',
        WantBlock: 'want to Report',
        ThisFriend: 'this feed?',
        Confirm: 'CONFIRM',
    },
    BlockProfile: {
        ReportUser: 'You have Report this user.',
        AreSure: 'Are you sure you',
        WantBlock: 'want to Report',
        ThisFriend: 'this profile?',
        Confirm: 'CONFIRM',
    },
    BlockUser: {
        ReportUser: 'You have Block this user.',
        AreSure: 'Are you sure you',
        WantBlock: 'want to Block',
        ThisFriend: 'this feed?',
        Confirm: 'CONFIRM',
    },
    BlockList: {
        BlockList: 'Block List',
        YearsOld: 'years old',
        NoData: 'No Data Found.',
    },
    ChatScreen: {
        Chat: 'Chat',
        OnlineUser: 'Online Users',
        NoData: 'No Users Found.',
        Subscribe: 'Subscribe',
        AccessFeature: 'To access all features on Afronection, go to subscription and select a plan that suits you.',
        Ok: 'Ok',
        TryAgain: 'Please try again',
    },
    CreateNewFeed: {
        FeedAdded: 'Your feed is added successfully.',
        ImageRequired: 'Image/Video is required.',
        NewFeed: 'Create New Feed',
        TitleRequired: 'Title is required',
        Description: 'Description is required',
        AddImages: 'Click here to add images or',
        Videos: 'Videos',
        Create: 'CREATE',
    },
    DeleteFriend: {
        DeletedFriend: 'You have deleted friend successfully.',
        AreSure: 'Are you sure you',
        DeleteThis: 'want to delete this',
        Friend: 'friend?',
        Confirm: 'CONFIRM',
    },
    DeleteFriendRequest: {
        DeletedFriend: 'You have deleted friend successfully.',
        AreSure: 'Are you sure you',
        DeleteThis: 'want to delete this',
        Friend: 'friend?',
        Confirm: 'CONFIRM',
    },
    Discover: {
        Discover: 'Discover',
        Years: 'years old',
        NoData: 'No Data Found.',
        SortName: 'Sort by name',
        SortAge: 'Sort by age',
        SortDistance: 'Sort by distance',
    },
    EditFeed: {
        EditFeed: 'Edit Feed',
        TitleRequired: 'Title is required',
        Description: 'Description is required',
        ClickImages: 'Click here to add images',
        ClickVideos: 'Click here to add Videos',
        EDIT: 'EDIT',
        FeedUpdated: 'Your feed is updated successfully.',
    },
    ForgotPassword: {
        EmailRequired: 'Email is required',
        EmailSent: 'Email has been sent',
        EmailAddress: 'Enter the email address associated with your account.',
        EmailReset: 'We will email you a link to reset your password.',
        Send: 'SEND'
    },
    ForgotPassword2: {
        OtpIncorrect: 'Entered OTP is incorrect.',
        NewPasswordRequired: 'New password is required',
        PasswordUpdate: 'Your password is updated successfully',
        ChangePassword: ' Change Password',
        Send: 'SEND',
    },
    LikeMatch: {
        HaveLiked: 'You Have Liked',
        NowChat: 'Now you can chat',
        With: 'with',
        Subscribe: 'Subscribe',
        AccessFeatures: 'To access all features on Afronection, go to subscription and select a plan that suits you.',
        StartChatting: 'START CHATTING',
        SendRequest: 'SEND FRIEND REQUEST',
        SentFriendRequest: 'You have already sent a friend request to the user',
        ProfileFriend: 'Profile is already in your friend list.',
        NotFriend: 'You are not friend',
        SentSuccessfully: 'You have sent a friend request successfully.',
        HaveBlocked: 'You have blocked ',
        ProfileBlockedWWW: 'Your Profile is blocked by ',
    },
    MyDashboard: {
        WhatIs: 'What Is New?',
        ShowAll: 'Show All',
        NoUsers: 'No Users Found.',
        RECENTFEED: 'RECENT FEED',
        Readmore: '..Read more',
        NoFeed: 'No Feed Found.',
    },
    DashboardSearch: {
        Search: 'Search',
        Country: 'Country',
        Age: 'Age between',
        ShowAge: 'show age',
        Min: 'min 18+',
        More: 'More Filters',
        Gender: 'Gender',
        Men: 'Men',
        Women: 'Women',
        Any: 'Any',
        Smoking: 'Smoking',
        Yes: 'Yes',
        No: 'No',
        Drinking: 'Drinking',
        Moderate: 'Moderate',
        Educational: 'Educational Qualifications',
        Hobbies: 'Hobbies',
        SelectHobby: 'Select Hobby',
        Recent: 'Recent Viewed',
        Years: 'years old',
        NoData: 'No Data Found',
        AccountDeactivate: 'Your account has been de-activated.',
        ProfileAdded: 'Profile is added in your favorite list successfully.',
        SentFriendRequest: 'You have sent a friend request successfully.',
        ProfileAlready: 'Profile is already in your favorite list.',
        ProfileFriendList: 'Profile is already in your friend list.',
        FriendRequestAlready: 'You have already sent a friend request to the user',
        ProfileDeletedList: 'Profile is deleted from your favorite list successfully.',

    },
    SentFriendRequest: {
        FriendRequest: 'Your Friend Request',
        SentSuccessful: 'Sent Successful to',
    },
    BlockFriendRequest: {
        AreYou: 'Are you sure you',
        Block: 'want to block',
        Friend: 'this friend?',
        Confirm: 'CONFIRM',
        BlockRequest: 'You have blocked friend request successfully.',
    },
    ChangePassword: {
        Change: 'Change Password',
        PasswordUpdate: 'Your password is updated successfully.',
        TryAgain: 'Please Try Again Later.',
    },
    DiscoverDetail: {
        Gender: 'Gender :',
        DOB: 'DOB :',
        Educational: 'Educational Qualification :',
        Height: 'Height :',
        NA: 'NA',
        Intro: 'Intro Video',
        Photos: 'Photos',
        Hobbies: 'Hobbies are',
        Friends: 'Friends are',
        Subscribe: 'Subscribe',
        RemoveFavourite: 'Remove Favourite',
        RemoveFavoriteList: 'Do you want to remove from favorite list ?',
        AccessFeature: 'To access all features on Afronection, go to subscription and select a plan that suits you.',
        ProfileAdded: 'Profile is added in your favorite list successfully.',
        RemoveProfile: 'You have removed profile from the favorite list successfully.',
        SentRequestUser: 'You have already sent a friend request to the user',
        ReceivedRequest: 'You have already received friend request from this user',
        ProfileList: 'Profile is already in your friend list.',
        addFriend: 'User is not a friend',
        alredyBlock: 'User block already',
        AlreadyReport: 'You have already Reported this feed.'


    },
    MyFavourites: {
        Favorites: 'Favorites',
        YearsOld: 'years old',
        NoData: 'No Data Found.',
        SortName: 'Sort by name',
        SortAge: 'Sort by age',
        SortDistance: 'Sort by distance',
    },
    MyFeed: {
        MyFeed: 'My Feed',
        AddNew: '+ Add New Feed',
        NoFeed: 'No Feeds Found.',
        DeleteFeed: 'Terms & Conditions',
        FeedDeleted: 'Your feed is deleted successfully .',
        DoDeletedFeed: "1.Eligibility. \n2.	Minimum Age.User of the Site must be at least 18 years old to use or to register at the Site for the Services. By using the Services on the Site, the User represents and warrants that he/ she is a minimum 18 years old. It is possible that certain Services may have other age requirements and such other age requirements are stated at the relevant places. \n3.	Marital Status. By requesting to use, registering to use, or using the Services, the User represents and warrants that the User is not married or is divorced. If the User is not legally divorced, then the Services will not be available for the User till the divorce is legally achieved. \n4.	Criminal History. By requesting to use, registering to use, and/or using the Service, the User represents and warrants that the User has never been convicted under any law governing us or the User. Afronection reserves the right to conduct a criminal background check, at any time and using available public records, to confirm possibility of misrepresentation. By agreeing to these Terms and Conditions, the User consents to and authorises such check. \n5.	Verification. By agreeing to the Terms and Conditions, User hereby authorises Afronection(and its third party authentication agency) to conduct verification checks on the User/ You. The verification process is critical/ important for receiving the complete set of Services offered at the Site by Afronection. The verification process is initiated and performed if: \n1.Specifically asked by You to receive the defined set of Services offered at the Site; \n2.	Afronection, at its sole discretion decides to conduct a Verification check whenever deemed necessary. \nUse of Site and Service. \n1.	Information Submitted. The User is solely responsible for, and assume all liability regarding, (i) the information and content provided at the Site for the Service; (ii) the information and content the User posts, transmits, publishes, shares or otherwise makes available (there after Post ) to TrulyMadly for the Services; (iii) User interactions with other Registered Users through the Services; and (iv) the information provided in the Personality Assessment. The Site shares User information with the specific Users matches. \n2.	Risk Assumption and Precautions. All risks when using the Services and the Site, including but not limited to all of the risks associated with any online or offline interactions with others, including meeting other matches remain with the User. The User is expected to use his / her best judgement in experiencing any of the benefits/ requirements of the Services. The User agrees to take all necessary precautions when meeting individuals through the Site and under the Services. In addition, the User agrees and confirms to review and follow the recommendations set forth in the Site as pointers to Safety and/ or mailed to User from time to time. The User undertakes to adhere to the Safety pointers and shall all times be responsible for all outcomes of meeting/ sharing information and/ or being in a short or a long term relationship through the Services/ Site. It is accepted and understood by the User that at all times the User shall use his/ her judgement and discretion in receiving the Services through the Site or proceeding with a match and/ or deciding to be in a relationship with a match here from.",
    },
    MyFeedCommentReply: {
        Reply: 'Reply',
        NoReply: 'No reply found',
        ReplySuccessfully: 'Your reply is added successfully.',
        LikedSuccessfully: 'You have liked reply successfully.',
        UnlikedSuccessfully: 'You have Unliked reply successfully.',
        DeletedSuccessfully: 'Your reply is deleted successfully.',
        UpdatedSuccessfully: 'Your reply is updated successfully.',
        DeleteReply: 'Delete Reply',
        DoDeleteReply: 'Do you want to delete the reply ?',
    },
    MyFeedCommentScreen: {
        Comments: 'Comments',
        NoData: 'No Data Found',
    },
    MyFriendListNew: {
        MyFriends: 'My Friends',
        Friends: 'Friends',
        NewRequest: 'New Request',
        YearsOld: 'years old',
        NoData: 'No Data Found.',
        SubscribePlan: 'Please Subscribe plan to send message.',
    },
    MyFriends: {
        My: 'My Friends'
    },
    MyFriendsList: {
        NoData: 'No Data Found',
        YearsOld: 'years old',
    },
    MyMatch: {
        MyMatch: 'My Match',
        YearsOld: 'years old',
        NoData: 'No Data Found.',
        SortValue: 'Sort by match value',
        SortName: 'Sort by name',
        SortAge: 'Sort by age',
        SortDistance: 'Sort by distance',
        TryAgain: 'Please try again',
    },
    MyNewFriendRequestListNew: {
        NoData: 'No Data Found.',
        YearsOld: 'years old',
        NewRequest: 'New Request',
        Friends: 'Friends',
        Yes: 'Yes',
        No: 'No',
        Ok: 'ok',
        MyFriends: 'My Friends',
        FriendRequestAccept: 'friend request accepted',
        AcceptedSuccessfully: 'You have accepted friend request successfully.',
        SubscribePlan: 'Please subscribe plan to delete friend request.',
        CannotBlockUser: 'You can not block as user is not in your friend list.',
        AcceptFriend: 'Accept friend',
        DoAcceptRequest: 'Do you want to accept the friend request ?',
        Subscribe: 'Subscribe',
        AccessFeatures: 'To access all features on Afronection, go to subscription and select a plan that suits you.',
    },
    Notification: {
        Notification: 'Notification',
        NoData: 'No Data Found.',
        SortDate: 'Sort by date',
    },
    PaymentFailure: {
        PaymentFailed: 'Payment Failed',
        SORRY: 'SORRY!',
        Payment: 'Payment',
        TryAgain: 'TRY AGAIN',
    },
    PaymentHistory: {
        PaymentHistory: 'Payment History',
        SortD: 'Sort by date',
        NoData: 'No Data Found.',
        ApproveRejected: 'Approve rejected',
        Approved: 'Approved',
        ApprovePending: 'Approve pending',
        To: 'To',
        Free: 'Free',
    },
    NewFriendRequestList: {
        Years: 'years old',
        NotifyMessage: 'friend request accepted',
        NotifyMessage1: 'You have accepted friend request sucessfully.',
        AlertMessage: 'Delete friend',
        AlertMessage1: 'Do you want to accept the friend request ?',
    },
    PaymentSuccess: {
        Payment: 'Payment',
        Congratulation: 'CONGRATULATION',
        HaveSubscribed: 'You have subscribed',
        PlanSuccessfully: 'plan successfully.',
        BackHome: 'BACK TO HOME',
    },
    RecentFeedCommentEdit: {
        Edit: 'Edit',
        EditComment: 'Edit Comment',
        UpdatedSuccessfully: 'Your comment is updated successfully.',
    },
    RecentFeedReplyEdit: {
        Edit: 'Edit',
        EditReply: 'Edit Reply',
        ReplySuccessfully: 'Your reply is updated sucessfully.'
    },
    PaymentMethods: {
        Checkout: 'PROCEED TO CHECKOUT',
        Submit: 'SUBMIT',
        MobilePayment: 'Enter your mobile number used for this payment',
        VerifyPayment: 'This helps us to verify your payment quickly',
        From: 'from:',
        MobileNumberPayment: 'Enter your mobile number used to make payment',
        Transaction: 'Your transaction',
        UploadImage: 'Upload clear image of',
        Screenshot: 'Please take a screenshot of your transaction and upload it below',
        Activate: 'activate you Afronection Account',
        PaymentProof: ' Upload proof of your payment. We will',
        Number: '068354234',
        MbampayPayment: 'Please make payment to our Mpamba pay number',
        MpambaPay: 'Mpamba Pay',
        AitelPayment: 'Please make payment to our Airtel number',
        AirtelMoney: 'Airtel Money',
        ExpiryDate: 'Expiry date is required.',
        Cvv: 'CVV',
        Expiry: 'Expiry',
        CardNumberRequired: 'Card number is required.',
        CardNumber: 'Card Number',
        Card: 'Debit/Credit card',
        PayPal: 'PayPal',
        AmountPay: 'Amount to Pay',
        PaymentMethods: 'Payment Methods',
        SendNotification: 'We will send you a notification as soon as your account is ready',
        ReceivedPayment: 'Payment is received successfully',
        TryAgain: 'Please try again later',
        SelectOne: 'Please Select Atleast One Method.',
        CvvRequired: 'Cvv is required',
        PhoneNumberRequired: 'Phone number is required.',
        ImageRequired: 'Image is required.',
    },
    EditProfile: {
        UpdateProfile: 'UPDATE MY PROFILE',
        ManageIntrest: 'Manage Social Interest',
        ManageHabit: 'Manage Social Habits',
        ManageEducation: 'Manage Education',
        ManageShow: 'Manage Show Me',
        Add: 'Add',
        DeleteHobby: 'Delete Hobby',
        DoDeleteHobby: 'Do you want to delete the Hobby?',
        ManageHobbies: 'Manage Hobbies',
        DeletePhoto: 'Delete Photo',
        DoDeletePhoto: 'Do you want to delete the photo?',
        ManagePhotos: 'Manage Photos',
        Edit: 'Edit',
        Delete: 'Delete',
        DoDeleteVideo: 'Do you want to delete the Video?',
        DeleteVideo: 'Delete Video',
        IntroVideo: 'Intro Video',
        Country: 'Country',
        HeightIs: 'Height is required.',
        Height: 'Height',
        DescriptionIs: 'Description is required.',
        Description: 'Description',
        Dob: 'Date of Birth',
        Address: 'Address',
        Gender: 'Gender',
        PhoneIs: 'Phone number is required.',
        Phone: 'Phone',
        Email: 'Email Address',
        NickNameIs: 'NickName is required.',
        NickName: 'Nick Name',
        FullNameIs: 'Fullname is required.',
        FullName: 'Full Name',
        CountryRequired: 'Country is required.',
        HobbyAdded: 'Your hobby is added successfully.',
        Error: 'Error.',
        HobbyAlready: 'Hobby is already added',
        PhotoDeleted: 'Your photo is deleted successfully.',
        VideoDeleted: 'Your Video is deleted successfully.',
        HobbyDeleted: 'Your hobby is deleted successfully.',
        HobbyUpdated: 'Your hobby is updated successfully.',
        PhotoUpdated: 'Your photo is updated successfully.',
        PhotoAdeed: 'Your photo is added successfully.',
        VideoAdded: 'Your Video is added successfully.',
        ProfileUpdated: 'Your profile is updated successfully.',
        SelectGender: 'Please Select Gender.',
        SelectSingle: 'Please Select a single option.',
        EducationalRequired: 'Educational qualification is required.',
        HabitsRequired: 'Social habits are required.',
        InterestRequired: 'Interest is required.',
        BirthDateBe: 'Birth date should be greater or equals to 18.',
        HeightFormat: "Please enter proper height format . For Example(5'3)",
    },
    DiscoverDetailFriend: {
        ProfileList: 'Profile is already in your friend list.',
        UserFriendReq: 'You have already sent a friend request to the user',
        RemoveProfileFav: 'You have removed profile from the favorite list successfully.',
        ProfileAddFav: 'Profile is added in your favorite list successfully.',
        Subscribe: 'Subscribe',
        AcessSubFeatures: 'To access all features on Afronection, go to subscription and select a plan that suits you.',
        RemoveFav: 'Remove Favourite',
        RemoveFavList: 'Do you want to remove from favorite list ?',
        Gender: 'Gender : ',
        Dob: 'Dob :',
        Education: 'Educational Qualification :',
        Height: 'Height : ',
        IntroVideo: 'Intro Video',
        Photos: 'Photos',
        HobbiesAre: 'Hobbies are',
        FriendsAre: 'Friends are',
    },
    RecentFeedComment: {
        NoComment: 'No comment found',
        DODeleteComment: 'Do you want to delete the comment ?',
        DeleteComment: 'Delete Comment',
        Comments: 'Comments',
        CommentUpdated: 'Your comment is updated successfully.',
        UnlikeComment: 'You have Unliked comment successfully.',
        LikedComment: 'You have liked comment successfully.',
        CommentAdded: 'Your comment is added successfully.',
        CommentDeleted: 'Your comment is deleted successfully.',
        AlreadyReported: 'You have already Reported this feed.',
    },
    RecentFeedCommentReply: {
        ReplyAdded: 'Your reply is added successfully.',
        LikedReplyed: 'You have liked reply successfully.',
        UnlikedReplyed: 'You have Unliked reply successfully.',
        ReplyDeleted: 'Your reply is deleted successfully.',
        ReplyUpdated: 'Your reply is updated successfully.',
        Reply: 'Reply',
        DoDeleteReply: 'Do you want to delete the Reply ?',
        DeleteReply: 'Delete Reply',
        NoReply: 'No reply found',
    },
    RecentFeedDescription: {
        LikeFeed: 'You have liked feed successfully.',
        UnlikeFeed: 'You have unliked feed successfully.',
        NoData: 'No Data Found',
    },
    randomAction: {
        title: 'title',
        man: 'Man',
        male: 'Male',
        india: "India",
        malawi: "Malawi",
        knitting: "knitting",
        cooking: "cooking",


    },
    DiscoverAction: {
        man: 'Man',
    }
}